# Colors (Taikami)

[colors.primary]
background = "#242424"
foreground = "#fdfbf9"
dim_foreground = "#8c9379"

[colors.cursor]
text = "#242424"
cursor = "#fdfbf9"

[colors.vi_mode_cursor]
text = "#242424"
cursor = "#fdfbf9"

[colors.selection]
text = "CellForeground"
background = "#8c9379"

[colors.normal]
black = "#1f2022"
red = "#cf8058"
green = "#a3bf78"
yellow = "#b1b493"
blue = "#d1a084"
magenta = "#d2ab93"
cyan = "#bdc6ae"
white = "#E6CBB4"

[colors.bright]
black = "#8c9379"
red = "#e7b59c"
green = "#cedeb4"
yellow = "#d9dac8"
blue = "#ecd3c5"
magenta = "#eeddd3"
cyan = "#e9ece3"
white = "#fdfbf9"
