[window]
opacity = 0.9

[colors]
transparent_background_colors = true

[colors.primary]
background = "#1d1d1d"
foreground = "#DCDFE4"

[colors.normal]
black = "#1d1d1d"
red = "#F28A8A"
green = "#92C88B"
yellow = "#FFB58A"
blue = "#8AB8FF"
magenta = "#FF9BE2"
cyan = "#C89BFF"
white = "#A3A3B3"

[colors.bright]
black = "#212126"
red = "#F79999"
green = "#A0D0A0"
yellow = "#FFC4A2"
blue = "#ADC8FF"
magenta = "#FFB0F0"
cyan = "#D0AAFF"
white = "#E9ECF2"